In [10]:
import pandas as pd

X= [ 4, 5, 8, 10, 11]
y=  [50, 48, 45 , 42, 41]
df = pd.DataFrame(data=[X,y]).transpose()

In [11]:
df.head()

    0   1
0   4  50
1   5  48
2   8  45
3  10  42
4  11  41

In [12]:
df.corr()

          0         1
0  1.000000 -0.996382
1 -0.996382  1.000000